import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../api/client";

function Orders() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; api.orders.list().then((data) => { if (active) setOrders(data); }).catch((requestError) => { if (active) setError(requestError.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  return <main className="min-h-screen bg-gray-50 px-6 py-12"><div className="mx-auto max-w-5xl"><div className="mb-8"><p className="font-semibold text-orange-500">Account</p><h1 className="mt-1 text-4xl font-bold">My Orders</h1><p className="mt-2 text-gray-500">Orders loaded from your store account.</p></div>{error && <p role="alert" className="mb-5 rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading ? <p className="rounded-xl border bg-white p-8 text-center text-slate-500">Loading orders…</p> : !orders.length ? <div className="rounded-2xl border bg-white p-12 text-center"><div className="text-5xl">📦</div><h2 className="mt-5 text-2xl font-bold">No orders yet</h2><Link to="/products" className="mt-6 inline-block rounded-xl bg-orange-500 px-7 py-3 font-semibold text-white">Start shopping</Link></div> : <div className="space-y-5">{orders.map((order) => <Link key={order.id} to={`/orders/${order.id}`} className="block overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:border-orange-300"><div className="flex flex-col justify-between gap-4 border-b bg-gray-50 p-5 sm:flex-row sm:items-center"><div><p className="text-sm text-gray-500">Order ID</p><p className="mt-1 font-bold">{order.id}</p></div><div><p className="text-sm text-gray-500">Order date</p><p className="mt-1 font-medium">{order.date}</p></div><span className="w-fit rounded-full bg-orange-50 px-3 py-1 text-xs font-semibold text-orange-700">{order.status}</span></div><div className="divide-y">{order.items.map((item) => <div key={item.id} className="flex items-center gap-4 p-5"><div className="h-16 w-16 overflow-hidden rounded-lg bg-slate-100">{item.image && <img src={item.image} alt={item.name} className="h-full w-full object-cover" />}</div><div className="flex flex-1 items-center justify-between gap-3"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-slate-500">₹{item.price} × {item.quantity}</p></div><p className="font-bold">₹{(item.price * item.quantity).toLocaleString("en-IN")}</p></div></div>)}</div><div className="flex justify-between border-t p-5"><span className="text-slate-500">Total</span><span className="font-bold text-orange-600">₹{order.total.toLocaleString("en-IN")}</span></div></Link>)}</div>}</div></main>;
}
export default Orders;
