import { useState } from "react";
import {
  Link,
  useLocation,
  useNavigate,
  useSearchParams
} from "react-router-dom";
import { api } from "../../api/client";

function Register() {
  const location = useLocation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const role =
    searchParams.get("role") === "vendor" ? "vendor" : "customer";

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [showPassword, setShowPassword] = useState(false);

  const [storeName, setStoreName] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [createdTenantId, setCreatedTenantId] = useState("");
  const [loading, setLoading] = useState(false);

  const handleRegister = async (event) => {
    event.preventDefault();

    setError("");
    setSuccess("");
    setCreatedTenantId("");

    if (password.length < 8) {
      return setError("Password must be at least 8 characters.");
    }

    const payload = {
      name: name.trim(),
      email: email.trim(),
      password,
      role: role === "vendor" ? "seller" : "customer"
    };

    if (role === "vendor") {
      if (!storeName.trim()) {
        return setError("Enter your store name.");
      }

      payload.storeName = storeName.trim();
    }

    setLoading(true);

    try {
      const result = await api.auth.register(payload);

      // Customer registration successful
      // Redirect directly to home page
      if (role === "customer") {
        navigate("/login");
        return;
      }

      // Vendor registration flow remains same
      setSuccess(
        `${result.message} Your store has been created. Sign in after an administrator approves it.`
      );

      setCreatedTenantId(result.tenant?._id || "");

      setPassword("");
    } catch (requestError) {
      setError(
        requestError.message || "Could not create your account."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-10 sm:px-6">
      <div className="w-full max-w-xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8">

        <div className="text-center">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-500 text-2xl text-white">
            S
          </div>

          <p className="mt-4 text-sm font-semibold text-orange-600">
            Join ShopSaaS
          </p>

          <h1 className="mt-1 text-3xl font-bold">
            {role === "vendor"
              ? "Create your seller account"
              : "Create your account"}
          </h1>

          <p className="mt-2 text-gray-500">
            {role === "vendor"
              ? "Set up your store workspace."
              : "Create a customer account to shop and place orders."}
          </p>
        </div>

        {error && (
          <div
            role="alert"
            className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-700"
          >
            {error}
          </div>
        )}

        {success && (
          <div
            role="status"
            className="mt-6 rounded-lg bg-green-50 p-3 text-sm text-green-800"
          >
            {success}

            <Link
              to={`/login?role=${role}`}
              state={{
                from:
                  role === "customer"
                    ? location.state?.from
                    : undefined
              }}
              className="ml-1 font-semibold underline"
            >
              Go to {role} login
            </Link>

            {createdTenantId && (
              <div className="mt-3 border-t border-green-200 pt-3">
                <p className="font-semibold">
                  Your generated store ID
                </p>

                <code className="mt-1 block break-all rounded bg-white p-2 text-xs">
                  {createdTenantId}
                </code>

                <p className="mt-2 text-xs">
                  This ID was generated by the backend and linked
                  to your seller account.
                </p>
              </div>
            )}
          </div>
        )}

        <form
          onSubmit={handleRegister}
          className="mt-8 space-y-5"
        >
          {role === "vendor" ? (
            <p className="rounded-xl bg-orange-50 p-4 text-sm text-orange-800">
              Seller registration · Your store needs admin approval
              before you can log in.
            </p>
          ) : (
            <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">
              Customer account · No account type or store ID entry
              is needed.
            </p>
          )}

          <label className="block text-sm font-medium">
            Full name

            <input
              required
              autoComplete="name"
              value={name}
              onChange={(event) =>
                setName(event.target.value)
              }
              className="mt-2 w-full rounded-lg border px-4 py-3"
            />
          </label>

          <label className="block text-sm font-medium">
            Email

            <input
              type="email"
              required
              autoComplete="email"
              value={email}
              onChange={(event) =>
                setEmail(event.target.value)
              }
              className="mt-2 w-full rounded-lg border px-4 py-3"
            />
          </label>

          {role === "vendor" && (
            <>
              <label className="block text-sm font-medium">
                Store name

                <input
                  required
                  value={storeName}
                  onChange={(event) =>
                    setStoreName(event.target.value)
                  }
                  placeholder="My Store"
                  className="mt-2 w-full rounded-lg border px-4 py-3"
                />
              </label>

              <p className="rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">
                New stores need administrator approval before the
                owner can sign in.
              </p>
            </>
          )}

          <label className="block text-sm font-medium">
            Password

            <div className="relative mt-2">
              <input
                type={showPassword ? "text" : "password"}
                required
                minLength={8}
                autoComplete="new-password"
                value={password}
                onChange={(event) =>
                  setPassword(event.target.value)
                }
                className="w-full rounded-lg border px-4 py-3 pr-12"
              />

              <button
                type="button"
                onClick={() =>
                  setShowPassword((previous) => !previous)
                }
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
                aria-label={
                  showPassword
                    ? "Hide password"
                    : "Show password"
                }
              >
                {showPassword ? (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    className="h-5 w-5"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M3 3l18 18"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M10.58 10.58a2 2 0 002.83 2.83"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M9.88 4.24A10.94 10.94 0 0112 4c7 0 10 8 10 8a18.45 18.45 0 01-3.08 4.38"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M6.61 6.61C3.91 8.33 2 12 2 12s3 8 10 8a10.94 10.94 0 004.12-.8"
                    />
                  </svg>
                ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    className="h-5 w-5"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12z"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="3"
                    />
                  </svg>
                )}
              </button>
            </div>

            <span className="mt-1 block text-xs font-normal text-slate-500">
              Use uppercase and lowercase letters, a number and
              one of @$!%*?&.
            </span>
          </label>

          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-lg bg-orange-500 py-3 font-semibold text-white transition hover:bg-orange-600 disabled:opacity-60"
          >
            {loading
              ? "Creating account…"
              : "Create Account"}
          </button>
        </form>

        <div className="mt-6 flex flex-col items-center gap-2 border-t pt-5 text-center text-sm text-gray-500">

          <p>
            Already have an account?{" "}
            <Link
              to={`/login?role=${role}`}
              className="font-semibold text-orange-500 hover:underline"
            >
              Log in
            </Link>
          </p>

          {role === "customer" ? (
            <p>
              Want to sell?{" "}
              <Link
                to="/signup?role=vendor"
                className="font-semibold text-orange-500 hover:underline"
              >
                Create a seller account
              </Link>
            </p>
          ) : (
            <p>
              Want to shop?{" "}
              <Link
                to="/signup"
                className="font-semibold text-orange-500 hover:underline"
              >
                Customer signup
              </Link>
            </p>
          )}

          <p>
            Admin accounts are created by the platform administrator.{" "}
            <Link
              to="/admin/login"
              className="font-semibold text-orange-500 hover:underline"
            >
              Admin login
            </Link>
          </p>

        </div>
      </div>
    </main>
  );
}

export default Register;