import { useState } from "react";
import { Link, useLocation, useSearchParams } from "react-router-dom";
import { api } from "../../api/client";

function Register() {
  const location = useLocation();
  const [searchParams] = useSearchParams();
  const role = searchParams.get("role") === "vendor" ? "vendor" : "customer";
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [storeName, setStoreName] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [createdTenantId, setCreatedTenantId] = useState("");
  const [loading, setLoading] = useState(false);

  const handleRegister = async (event) => {
    event.preventDefault();
    setError("");
    setSuccess("");
    setCreatedTenantId("");
    if (password.length < 8) return setError("Password must be at least 8 characters.");
    const payload = { name: name.trim(), email: email.trim(), password, role: role === "vendor" ? "seller" : "customer" };
    if (role === "vendor") {
      if (!storeName.trim()) return setError("Enter your store name.");
      payload.storeName = storeName.trim();
    }
    setLoading(true);
    try {
      const result = await api.auth.register(payload);
      setSuccess(role === "vendor" ? `${result.message} Your store has been created. Sign in after an administrator approves it.` : `${result.message} Sign in to continue.`);
      setCreatedTenantId(result.tenant?._id || "");
      setPassword("");
    } catch (requestError) {
      setError(requestError.message || "Could not create your account.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-10 sm:px-6">
      <div className="w-full max-w-xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8">
        <div className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-500 text-2xl text-white">S</div><p className="mt-4 text-sm font-semibold text-orange-600">Join ShopSaaS</p><h1 className="mt-1 text-3xl font-bold">{role === "vendor" ? "Create your seller account" : "Create your account"}</h1><p className="mt-2 text-gray-500">{role === "vendor" ? "Set up your store workspace." : "Create a customer account to shop and place orders."}</p></div>
        {error && <div role="alert" className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
        {success && <div role="status" className="mt-6 rounded-lg bg-green-50 p-3 text-sm text-green-800">{success} <Link to={`/login?role=${role}`} state={{ from: role === "customer" ? location.state?.from : undefined }} className="ml-1 font-semibold underline">Go to {role} login</Link>{createdTenantId && <div className="mt-3 border-t border-green-200 pt-3"><p className="font-semibold">Your generated store ID</p><code className="mt-1 block break-all rounded bg-white p-2 text-xs">{createdTenantId}</code><p className="mt-2 text-xs">This ID was generated by the backend and linked to your seller account.</p></div>}</div>}
        <form onSubmit={handleRegister} className="mt-8 space-y-5">
          {role === "vendor" ? <p className="rounded-xl bg-orange-50 p-4 text-sm text-orange-800">Seller registration · Your store needs admin approval before you can log in.</p> : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Customer account · No account type or store ID entry is needed.</p>}
          <label className="block text-sm font-medium">Full name<input required autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-lg border px-4 py-3" /></label>
          <label className="block text-sm font-medium">Email<input type="email" required autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-lg border px-4 py-3" /></label>
          {role === "vendor" && <>
            <label className="block text-sm font-medium">Store name<input required value={storeName} onChange={(event) => setStoreName(event.target.value)} placeholder="My Store" className="mt-2 w-full rounded-lg border px-4 py-3" /></label>
            <p className="rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">New stores need administrator approval before the owner can sign in.</p>
          </>}
          <label className="block text-sm font-medium">Password<input type="password" required minLength={8} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-lg border px-4 py-3" /><span className="mt-1 block text-xs font-normal text-slate-500">Use uppercase and lowercase letters, a number and one of @$!%*?&amp;.</span></label>
          <button type="submit" disabled={loading} className="w-full rounded-lg bg-orange-500 py-3 font-semibold text-white transition hover:bg-orange-600 disabled:opacity-60">{loading ? "Creating account…" : "Create Account"}</button>
        </form>
        <div className="mt-6 flex flex-col items-center gap-2 border-t pt-5 text-center text-sm text-gray-500"><p>Already have an account? <Link to={`/login?role=${role}`} className="font-semibold text-orange-500 hover:underline">Log in</Link></p>{role === "customer" ? <p>Want to sell? <Link to="/signup?role=vendor" className="font-semibold text-orange-500 hover:underline">Create a seller account</Link></p> : <p>Want to shop? <Link to="/signup" className="font-semibold text-orange-500 hover:underline">Customer signup</Link></p>}<p>Admin accounts are created by the platform administrator. <Link to="/admin/login" className="font-semibold text-orange-500 hover:underline">Admin login</Link></p></div>
      </div>
    </main>
  );
}

export default Register;
